import { DocumentReaderItem } from '@/components/document-reader';

export const INITIAL_DEMO_DOCUMENTS: DocumentReaderItem[] = [
  {
    id: 'doc-seed-art-01',
    title: 'Enterprise AI & Research Governance Policy',
    subtitle: 'Research Ethics, Machine Learning & Standard Protocols',
    type: 'article',
    icon: '📰',
    fileSize: '1.4 MB',
    isSigned: true,
    employeeEmail: 'elena.vance@enterprise.com',
    employeeName: 'Dr. Elena Vance',
    statusNote: 'Approved by AI Ethics Board',
    fullContent: {
      category: 'Research & AI Policy',
      date: '15/09/2026',
      authorOrIssuer: 'Enterprise AI Ethics Board',
      sections: [
        {
          heading: '1. Purpose & Scope',
          body: 'This operational policy governs the responsible deployment of deep learning models, generative AI architectures, and proprietary neural embeddings across all enterprise research labs and internal compute clusters.',
        },
        {
          heading: '2. Data Confidentiality & Model Training',
          body: 'Under no circumstances may client-confidential data, personally identifiable information (PII), or unredacted medical telemetry be ingested into training runs without end-to-end cryptographic hashing and explicit Data Privacy Officer (DPO) clearance.',
        },
        {
          heading: '3. Model Registry & Audit Trails',
          body: 'Every production artifact must maintain an immutable cryptographic fingerprint, traceable training hyperparameter log, and automated bias evaluation score before promotion to production clusters.',
        },
      ],
      metadata: {
        department: 'AI & Cognitive Research',
        classification: 'Confidential Internal',
        version: 'v3.2',
      },
    },
  },
  {
    id: 'doc-seed-art-02',
    title: 'Information Security Protocols & Zero-Trust Blueprint',
    subtitle: 'Mandatory CISO Information Security Guidelines 2026',
    type: 'article',
    icon: '📰',
    fileSize: '2.1 MB',
    isSigned: true,
    employeeEmail: 'john.doe@enterprise.com',
    employeeName: 'John Doe',
    statusNote: 'Enterprise Verified',
    fullContent: {
      category: 'Cybersecurity & Infrastructure',
      date: '10/09/2026',
      authorOrIssuer: 'CISO Security Directorate',
      sections: [
        {
          heading: '1. Zero-Trust Architecture Mandate',
          body: 'All staff connections must authenticate through mutual TLS (mTLS) with hardware-backed WebAuthn credentials. Internal network perimeter trust is strictly deprecated.',
        },
        {
          heading: '2. Document Vault Security & Encryption',
          body: 'Files uploaded to the enterprise repository undergo AES-256-GCM envelope encryption at rest, accompanied by automated DLP malware scans and heuristic anomaly detection.',
        },
      ],
      metadata: {
        department: 'Security Operations (SecOps)',
        compliance: 'ISO 27001 / SOC 2 Type II',
      },
    },
  },
  {
    id: 'doc-seed-art-03',
    title: 'Remote Work & Global Intellectual Property Policy',
    subtitle: 'HR Workspace Conduct & Hardware Security Standard',
    type: 'article',
    icon: '📰',
    fileSize: '980 KB',
    isSigned: false,
    employeeEmail: 'sarah.smith@enterprise.com',
    employeeName: 'Sarah Smith',
    statusNote: 'Annual Revision Pending',
    fullContent: {
      category: 'Human Resources & Workplace',
      date: '02/09/2026',
      authorOrIssuer: 'Global People Operations',
      sections: [
        {
          heading: '1. Remote Workspace Standards',
          body: 'Employees operating remotely are required to maintain a secure physical workstation free from unauthorized visual eavesdropping when inspecting proprietary materials.',
        },
        {
          heading: '2. Intellectual Property Protection',
          body: 'All intellectual output, inventions, software code, research memos, and analytical models developed on enterprise resources remain the sole property of the corporation.',
        },
      ],
      metadata: {
        department: 'Human Resources',
        effectiveDate: '01/01/2026',
      },
    },
  },
  {
    id: 'doc-seed-pdf-01',
    title: 'Master Enterprise Services Agreement (MSA 2026)',
    subtitle: 'Corporate Legal Binding Terms & Service Level Agreement',
    type: 'pdf',
    icon: '📄',
    fileSize: '3.4 MB',
    isSigned: true,
    employeeEmail: 'john.doe@enterprise.com',
    employeeName: 'John Doe',
    statusNote: 'Signed & Legally Executed',
    fullContent: {
      category: 'Legal & Contracts',
      date: '18/08/2026',
      authorOrIssuer: 'Enterprise Legal Affairs',
      sections: [
        {
          heading: 'Article I: Covenant of Services',
          body: 'This Master Enterprise Services Agreement defines the governance model, guaranteed 99.99% infrastructure uptime SLAs, data handling warranties, and reciprocal indemnity obligations.',
        },
      ],
    },
  },
  {
    id: 'doc-seed-pdf-02',
    title: 'DocuVault System Overview & Compliance Handbook',
    subtitle: 'Platform Architecture & Certified Administrative Reference',
    type: 'pdf',
    icon: '📄',
    fileSize: '2.8 MB',
    isSigned: true,
    employeeEmail: 'admin@enterprise.com',
    employeeName: 'System Administrator',
    statusNote: 'Core Reference Manual',
    fullContent: {
      category: 'System Documentation',
      date: '01/08/2026',
      authorOrIssuer: 'DocuVault Core Architecture Team',
      sections: [
        {
          heading: 'System Operations & Ingestion Pipeline',
          body: 'DocuVault processes incoming PDF documents through high-fidelity rendering buffers, extracting optical character layers while securing cryptographic signatures.',
        },
      ],
    },
  },
  {
    id: 'doc-seed-pdf-03',
    title: 'Q3 Corporate Financial & Audit Statement',
    subtitle: 'Quarterly Operating Balance, Projections & Tax Review',
    type: 'pdf',
    icon: '📄',
    fileSize: '4.6 MB',
    isSigned: false,
    employeeEmail: 'sarah.smith@enterprise.com',
    employeeName: 'Sarah Smith',
    statusNote: 'Awaiting Audit Signature',
    fullContent: {
      category: 'Finance & Treasury',
      date: '28/08/2026',
      authorOrIssuer: 'Corporate Finance Directorate',
      sections: [
        {
          heading: 'Consolidated Statement of Operations',
          body: 'Comprehensive breakdown of operating revenues, EBITDA margins, capital expenditures (CapEx) on cloud infrastructure, and research amortizations.',
        },
      ],
    },
  },
  {
    id: 'doc-seed-docx-01',
    title: 'Engineering Architecture Blueprint v4.2',
    subtitle: 'Microservices, Event Streams & Sharded DB Schemas',
    type: 'docx',
    icon: '📘',
    fileSize: '1.9 MB',
    isSigned: true,
    employeeEmail: 'michael.chen@enterprise.com',
    employeeName: 'Michael Chen',
    statusNote: 'Approved for Q4 Implementation',
    fullContent: {
      category: 'Software Engineering',
      date: '05/09/2026',
      authorOrIssuer: 'Principal System Architect',
      sections: [
        {
          heading: 'System Topology & Partitioning',
          body: 'Details the transition towards multi-region sharded collections with horizontal replication, event-driven indexing, and real-time push notifications.',
        },
      ],
    },
  },
  {
    id: 'doc-seed-docx-02',
    title: 'Annual Product Strategy & Roadmap Specifications',
    subtitle: 'Deliverables, Milestones & Engineering KPI Matrix',
    type: 'docx',
    icon: '📘',
    fileSize: '1.2 MB',
    isSigned: false,
    employeeEmail: 'sarah.smith@enterprise.com',
    employeeName: 'Sarah Smith',
    statusNote: 'Draft In Review',
    fullContent: {
      category: 'Product Management',
      date: '12/09/2026',
      authorOrIssuer: 'Strategic Product Operations',
      sections: [
        {
          heading: 'Strategic Milestones',
          body: 'Targeted delivery timeline for enhanced vector indexing, native dark-mode document reader, and enterprise bulk document export capabilities.',
        },
      ],
    },
  },
  {
    id: 'doc-seed-img-01',
    title: 'Headquarters Data Center & Network Topology',
    subtitle: 'Core Optical Fiber Routing & Redundant Power Grid',
    type: 'image',
    icon: '🖼️',
    fileSize: '4.8 MB',
    isSigned: true,
    employeeEmail: 'michael.chen@enterprise.com',
    employeeName: 'Michael Chen',
    previewImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    statusNote: 'Infrastructure Verified',
    fullContent: {
      category: 'Infrastructure & Hardware',
      date: '19/08/2026',
      authorOrIssuer: 'Network Infrastructure Team',
      sections: [
        {
          heading: 'Hardware Interconnects',
          body: 'Visual schematic showcasing dual redundant Tier-3 optical backbones, diesel backup generators, and isolated DMZ subnets.',
        },
      ],
    },
  },
  {
    id: 'doc-seed-img-02',
    title: 'Campus Emergency Evacuation & Safety Blueprint',
    subtitle: 'Facility Management, Primary Exits & Safe Zones',
    type: 'image',
    icon: '🖼️',
    fileSize: '2.5 MB',
    isSigned: true,
    employeeEmail: 'admin@enterprise.com',
    employeeName: 'System Administrator',
    previewImage: 'https://images.unsplash.com/photo-1524813686514-a57563d77d4c?w=800&auto=format&fit=crop&q=80',
    statusNote: 'Facility Certified',
    fullContent: {
      category: 'Facility & Safety',
      date: '14/07/2026',
      authorOrIssuer: 'Occupational Health & Safety (OHS)',
      sections: [
        {
          heading: 'Emergency Assembly Procedures',
          body: 'Clear architectural map illustrating primary fire egress routes, automated suppression systems, and designated assembly zone Alpha.',
        },
      ],
    },
  },
  {
    id: 'doc-seed-oth-01',
    title: 'Enterprise Cloud Drive & Media Repository Mirror',
    subtitle: 'Google Drive Repository • Shared Cloud Vault',
    type: 'link',
    icon: '🔗',
    fileSize: 'Google Drive',
    fileUrl: 'https://drive.google.com/drive/folders/enterprise-docuvault-shared',
    isSigned: true,
    employeeEmail: 'elena.vance@enterprise.com',
    employeeName: 'Dr. Elena Vance',
    statusNote: 'Verified Drive Link',
    fullContent: {
      category: 'Cloud Links & Drive',
      date: '20/09/2026',
      authorOrIssuer: 'Enterprise Cloud Services',
      sections: [
        {
          heading: 'Cloud Synchronization Hub',
          body: 'Direct connected portal for enterprise shared drives, media libraries, and distributed marketing assets.',
        },
      ],
    },
  },
  {
    id: 'doc-seed-vid-01',
    title: 'Enterprise Security Protocol & Compliance Walkthrough',
    subtitle: 'Mandatory Cyber Hygiene & Document Handling Briefing',
    type: 'video',
    icon: '🎥',
    fileSize: '48.5 MB',
    isSigned: true,
    employeeEmail: 'john.doe@enterprise.com',
    employeeName: 'John Doe',
    statusNote: 'Annual Security Certified',
    fullContent: {
      category: 'Training & Video Briefings',
      date: '22/09/2026',
      authorOrIssuer: 'Enterprise Cybersecurity Directorate',
      sections: [
        {
          heading: 'Video Synopsis & Key Requirements',
          body: 'Video walkthrough outlining zero-trust credentials, two-factor authentication, and safe handling of sensitive client documents across remote workstations.',
        },
      ],
    },
  },
];
